# fly.toml app configuration file generated for react-electionsim on 2023-11-02T13:55:10-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "react-electionsim"
primary_region = "iad"

[build]
  dockerfile = "DockerfileProd"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
