version: '3.8'
services:
  fastapi-backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app
    networks:
      - electionsim-network

  react-frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/:/srv/app
      - node_modules:/srv/app/node_modules
    networks:
      - electionsim-network

volumes:
  node_modules:

networks:
  electionsim-network:
    driver: bridge