name: Deploy Backend to Fly.io

on:
  push:
    branches:
      - staging
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to Fly.io
      run: flyctl deploy --dockerfile DockerfileProd
      working-directory: ./backend
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}